export enum EstadoSolicitacao {
  ABERTA = 'ABERTA',
  ORCADA = 'ORÇADA',
  APROVADA = 'APROVADA',
  REJEITADA = 'REJEITADA',
  REDIRECIONADA = 'REDIRECIONADA',
  ARRUMADA = 'ARRUMADA',
  PAGA = 'PAGA',
  FINALIZADA = 'FINALIZADA'
}